### ISSUE TITLE
Disparity in the generate function

### ISSUE THREAD

**Issue by IP1102** [huggingface/trl#1812] opened 2024-07-08 01:58 UTC
Hello, I have fine tuned a `[Code-T5](https://huggingface.co/Salesforce/codet5-small)` model on my custom dataset. Now while I was using `trl` to further train the fine tuned model to align it better, I noticed a very strange phenomenon. The `ppotrainer.generate` function generates something very different than what is generated if I use the model's generate function. To give you a background, here is what I have followed:

I loaded the model like the following:

```python
model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained("../ft-scripts/output")
tokenizer = AutoTokenizer.from_pretrained("../ft-scripts/output")
```

Here is the ppo config:

```python
config = PPOConfig(
    model_name="../ft-scripts/output",
    learning_rate=0.001,
    ppo_epochs=100,
    mini_batch_size=4,
    batch_size=8,
    gradient_accumulation_steps=1,
    ratio_threshold=200,
    early_stopping=True
)
ref_model = create_reference_model(model)
ppo_trainer = PPOTrainer(
    config,
    model,
    ref_model=ref_model,
    tokenizer=tokenizer,
    optimizer=Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=config.learning_rate)
)

generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
    "max_new_tokens": 512
}

```

To generate normally, I am using the following code:

```python
with torch.no_grad():
    gen_tokens = model.generate(tok_input, max_length = 512)
ft = tokenizer.decode(gen_tokens[0], skip_special_tokens=True)
print("Normal generation:")
print(ft)
```

And to generate with `trl`, 

```python
  print("PPO generation")
  gen_len = 512
  generation_kwargs["max_new_tokens"] = gen_len
  response = ppo_trainer.generate(list(tok_input), **generation_kwargs)
  ft_ppo = tokenizer.decode(response[0], skip_special_tokens=True)
  print(ft_ppo)         
```

I believe the use of `list` is being already addressed in this #793 

Now the output is like this:

```
Normal generation:
    private void doStart() {
        formatter = DateTimeFormat.forPattern(timeFormat).withZone(DateTimeZone.forID(timeZone));
        producerConfig.userAgent = "logback";
        producer = new LogProducer(producerConfig);
        producer.setProjectConfig(projectConfig);

        super.start();
    }

===============================================
PPO generation

    public void start();
    public void start());
    }); '=>'
```

Why such a disparity in the generated results when `generate` function under the hood anyway calls the model's `generate` method. Reference: https://github.com/huggingface/trl/blob/78045dedc8678af04f4e35ffe63f37be196a435b/trl/trainer/ppo_trainer.py#L575

Am I doing something wrong, or is there a bug?

**Comment by qgallouedec** [comment] 2024-10-07 12:12
Closing because the required elements to reproduce the reported bug have not been provided.

**Closed by qgallouedec** 2024-10-07 12:12 UTC
