### ISSUE TITLE
Issue with SFTTrainer on Falcon 7B using Flash Attention 2

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/trl#875] opened 2023-10-15 18:19 UTC
**Error**
```
ut_p, softmax_scale, causal, window_size, return_softmax)
     45 maybe_contiguous = lambda x: x.contiguous() if x.stride(-1) != 1 else x
     46 q, k, v = [maybe_contiguous(x) for x in (q, k, v)]
---> 47 out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
     48     q,
     49     k,
     50     v,
     51     None,
     52     dropout_p,
     53     softmax_scale,
     54     causal,
     55     window_size[0],
     56     window_size[1],
     57     return_softmax,
     58     None,
     59 )
     60 return out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state

TypeError: fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: Optional[torch.Tensor], arg4: float, arg5: float, arg6: bool, arg7: int, arg8: int, arg9: bool, arg10: Optional[torch.Generator]) -> List[torch.Tensor]
```

**Reproduction**
```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map='cuda',
    # torch_dtype=torch.bfloat16, #I also tried this, with the same error
    torch_dtype=torch.float16,
    use_flash_attention_2=True,
    cache_dir=cache_dir)

from transformers import Trainer
from trl import SFTTrainer

trainer = SFTTrainer(
    peft_config=config,
    dataset_text_field="text",
    max_seq_length=context_length,
    tokenizer=tokenizer,
    model=model,
    train_dataset=data["train"],
    eval_dataset=data["test"],
    args=transformers.TrainingArguments(
        max_steps=60, # comment this out after the first time you run. This is for testing!
        num_train_epochs=epochs,
        output_dir=save_dir,
        evaluation_strategy="steps",
        do_eval=True,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=4,
        per_device_eval_batch_size=batch_size,
        log_level="debug",
        optim="paged_adamw_8bit",
        save_steps=0.2,
        logging_steps=1,
        learning_rate=1e-4,
        eval_steps=0.2,
        fp16=True,
        max_grad_norm=0.3,
        warmup_ratio=0.03,
        lr_scheduler_type="constant",
    ),
    callbacks=[logging_callback],  # Add custom callback here
)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()
```

**System Details:**
Operating System: Linux
OS Version: 5.4.0-155-generic
Machine: x86_64
Processor: x86_64

Python Environment
Python Version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Executable: /usr/bin/python

CUDA & Hardware Information
CUDA Available: True
CUDA Version: 11.8
CUDA Device Count: 1
Current CUDA Device: 0
CUDA Device Name: NVIDIA RTX A6000

Transformers Library Information
Transformers Version: 4.34.0
flash-attn==2.3.2

**Comment by younesbelkada** [comment] 2023-10-15 18:41
Duplicate of https://github.com/huggingface/trl/issues/832, planning to look into it very soon (this week)

**Closed by younesbelkada** 2023-10-15 18:41 UTC
