### ISSUE TITLE
Memory flush warnings when using DPOTrainer with Deepspeed zero3

### ISSUE THREAD

**Issue by kangqi-ni** [huggingface/trl#1100] opened 2023-12-15 06:44 UTC
When I use DPOTrainer for training with deepspeed zero3, I encounter this warning multiple times: 1 pytorch allocator cache flushes since last step. this happens when there is high memory pressure and is detrimental to performance. if this is 
happening frequently consider adjusting settings to reduce memory consumption. If you are unable to make the cache flushes go away consider adding get_accelerator().empty_cache() calls in your training loop to ensure that all ranks flush their caches at the same time.

Is there a solve for that? I am using one batch size for each device so cannot decrease batch size any more.

**Comment by younesbelkada** [comment] 2023-12-20 19:40
Hi @kangqi-ni 
Thanks for the suggestion ! 
WDYT of adding `self.accelerator.empty_cache()` at the end of each training step @kashif ? Would this break the DPO Trainer?

**Comment by younesbelkada** [comment] 2023-12-20 19:47
@kangqi-ni can you point me to the `empty_cache` method? I can't find it in accelerate

**Comment by abhishekkrthakur** [comment] 2024-03-31 15:43
still an issue. with sft

**Comment by w5688414** [comment] 2024-04-28 01:20
I meeth the same problem, is there any solutions?

**Comment by qgallouedec** [comment] 2024-10-19 18:26
Currently I cannot reproduce this warning, if anyone has a setting that allows to reproduce it, please post here.

> consider adding get_accelerator().empty_cache() calls in your training loop to ensure that all ranks flush their caches at the same time.

According to [this comment](https://lightning.ai/forums/t/how-to-ensure-all-ranks-flush-their-caches-during-training-using-deepspeed-stage3/2843/2), clearing the cache requires synchronization and may adversely affect performance. Therefore, I don't think it's a good idea to add this. 

>  I am using one batch size for each device so cannot decrease batch size any more.

I don't think there's any solution if you have this warning and your batch size is already at 1.

**Comment by qgallouedec** [comment] 2024-11-22 17:42
Closing as not able to reproduce. Please re-open if you get a MRE

**Closed by qgallouedec** 2024-11-22 17:42 UTC
Labels: 🏋 DPO, ⏳ needs more info
