### ISSUE TITLE
[CLI] The CLI `SFT` does not work with quantization

### ISSUE THREAD

**Issue by August-murr** [huggingface/trl#2150] opened 2024-10-01 17:56 UTC
### System Info

This issue was tested on two setups:

- **Google Colab** with a single T4 GPU
- **Kaggle** with 2x T4 GPUs

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I have created two notebooks that reproduce the issue:

- [Colab Notebook](https://colab.research.google.com/drive/1jJttUiOaWsWpGm5eSLJlQ7tyH_S3atVh?usp=sharing)
- [Kaggle Notebook](https://www.kaggle.com/augustmurr/trl-cli-sft-quantization-error
)

### Expected behavior

The SFT command should support 4-bit and 8-bit quantization when using a LoRA adapter. but the model fails to properly quantize

**Comment by August-murr** [comment] 2024-10-08 09:22
> - TRL version: 0.12.0.dev0+51ca76b

`pip install trl` installs version `11.2`

but it gets more confusing, I'd appreciate if you explain this. when running `trl env` to get system configuration I get the error:
```
ValueError: Please use one of the supported commands, got env - supported commands are ['sft', 'dpo', 'chat', 'kto']
```

but when using 
```bash
pip install git+https://github.com/huggingface/trl.git
```

it installs `v0.12` and `trl env` works fine.
the part I don't understand is that in version `11.2` in [cli.py](https://github.com/huggingface/trl/blob/main/trl/commands/cli.py) the supported commands are:
```python
SUPPORTED_COMMANDS = ["sft", "dpo", "chat", "kto", "env"]
```
so why doesn't `trl env` work with version `11.2`?

**Comment by qgallouedec** [comment] 2024-10-08 09:24
> so why doesn't `trl env` work with version `11.2`?

It was only added in v0.12 (not release yet)

**Comment by qgallouedec** [comment] 2024-10-08 09:25
Share your system info with `transformers-cli env`, it's mostly the same

**Comment by August-murr** [comment] 2024-10-08 09:38
### Kaggle
- `transformers` version: 4.45.1
- Platform: Linux-5.15.154+-x86_64-with-glibc2.35
- Python version: 3.10.14
- Huggingface_hub version: 0.25.1
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.0 (True)
- Tensorflow version (GPU?): 2.16.1 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26.dev20240620
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla P100-PCIE-16GB

since trl version wasn't printed in this:
`!pip show trl`
Name: trl
Version: 0.11.2

### Colab
- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Tensorflow version (GPU?): 2.17.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (gpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla T4

trl version
Name: trl
Version: 0.11.2

**Comment by qgallouedec** [comment] 2024-10-08 09:41
When does the error occur? At the very beginning? Or at the end?

**Comment by August-murr** [comment] 2024-10-08 09:50
> When does the error occur? At the very beginning? Or at the end?

When the model is being loaded, before training starts it runs into an issue with bitsandbytes.

`TypeError: Object of type BitsAndBytesConfig is not JSON serializable`

all the example scripts use `AutoModelForCausalLM ` and don't run into quantization issues but this script initializes the model in the SFTTrainer which causes this issue.

**Comment by qgallouedec** [comment] 2024-10-08 10:16
Still can't reproduce. Here is what I've done

```
conda create -n tmp_env python=3.10
conda activate tmp_env
pip install bitsandbytes==0.44.1 datasets==3.0.1 dill==0.3.8 multiprocess==0.70.16 peft==0.13.0 pyarrow==17.0.0 shtab==1.7.1 trl==0.11.1 tyro==0.8.11 xxhash==3.5.0 huggingface_hub==0.25.1 accelerate==0.34.2 torch==2.4.0
trl sft --model_name_or_path "facebook/opt-125m"     --dataset_name "stanfordnlp/imdb"    --dataset_text_field "text"    --torch_dtype "bfloat16"    --output_dir "opt-sft-imdb_4bit"    --load_in_4bit    --use_peft    --lora_r 4
```

**Comment by August-murr** [comment] 2024-10-08 10:54
I guess it only happens on Free Tier instances with T4 and P100 and other 6-year-old GPUs and not on AWS H100 systems huh!

You can close this issue but if anybody else reported this issue on Colab or Kaggle, it's just a simple `AutoModelForCausalLM`.

Also, you should consider using PEFTs [`prepare_model_for_kbit_training`](https://huggingface.co/docs/peft/v0.13.0/en/package_reference/peft_model#peft.prepare_model_for_kbit_training) for other example scripts since it's recommended for quantized training tasks.

**Comment by qgallouedec** [comment] 2024-10-09 08:38
> Also, you should consider using PEFTs [`prepare_model_for_kbit_training`](https://huggingface.co/docs/peft/v0.13.0/en/package_reference/peft_model#peft.prepare_model_for_kbit_training) for other example scripts since it's recommended for quantized training tasks.

We use it actually:
https://github.com/huggingface/trl/blob/ed9ea74b62ea5aab3a2c597c4d73fadafc51f5dc/trl/trainer/sft_trainer.py#L261

Closing as not reproduced.

**Closed by qgallouedec** 2024-10-09 08:38 UTC
Labels: 🐛 bug, ⏳ needs more info, 📱 cli
