### ISSUE TITLE
Any config file?

### ISSUE THREAD

**Issue by Wallace-222** [huggingface/trl#661] opened 2023-08-18 13:35 UTC
Hello authors, 
Thanks for your wonderful project.
Can you recommend any config file here for the research project of De-detoxifying language models?
ACCELERATE_LOG_LEVEL=info accelerate launch --config_file {CONFIG} examples/toxicity/scripts/gpt-j-6b-toxicity.py --log_with wandb

**Comment by younesbelkada** [comment] 2023-08-18 14:34
Hi @Wallace-222 , thank you
I think that I have used the default accelerate config with multi-GPU, can you try that out and let us know if it works?
```bash
accelerate config
```
Then select multi-GPU, leave all the other options to default

**Comment by Wallace-222** [comment] 2023-08-19 11:36
It fails to run on 8 A40 GPUs. May I know what kinds of GPUs needed to run this experiment? Thanks a lot.

**Comment by younesbelkada** [comment] 2023-08-21 07:28
Hi @Wallace-222 
Can you share the error trace?

**Comment by younesbelkada** [comment] 2023-09-18 11:50
Closing for now, feel free to re-open if you think the issue is not solved

**Closed** 2023-09-18 11:50 UTC
