### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by DinhLuan14** [huggingface/trl#614] opened 2023-08-03 17:18 UTC
I've encountered a bug:

```stats = ppo_trainer.step(question_tensors, response_tensors, rewards)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 724, in step
    logprobs, logits, vpreds, _ = self.batched_forward_pass(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 952, in batched_forward_pass
    torch.cat(all_logprobs),
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

When running trl on the latest version 0.5.0. However, everything was working fine on the previous version git+https://github.com/lvwerra/trl.git@fead2c8c77b8b600a3900a94d18eb3451797e25b. So, what has happened?

**Comment by lvwerra** [comment] 2023-08-03 17:43
Can you provide a minimal reproducible script? Otherwise it is hard to know what's going on :)

**Comment by DinhLuan14** [comment] 2023-08-04 02:54
Here is the code i run:
```
from dataclasses import dataclass, field
from typing import Optional

import torch
from accelerate import Accelerator
from datasets import load_dataset
from peft import LoraConfig
from tqdm import tqdm
from transformers import StoppingCriteria, StoppingCriteriaList, Adafactor, AutoTokenizer, HfArgumentParser, pipeline
from trl import (AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer,
                 set_seed)
from trl.core import LengthSampler

tqdm.pandas()


@dataclass
class ScriptArguments:
    """
    The name of the Casual LM model we wish to fine with PPO
    """

    # NOTE: gpt2 models use Conv1D instead of Linear layers which are not yet supported in 8 bit mode
    # models like gpt-neo* models are more suitable.
    model_name: Optional[str] = field(default="", metadata={"help": "the model name"})
    tokenizer_name: Optional[str] = field(default="", metadata={"help": "the tokenizer name"})
    reward_model_name: Optional[str] = field(default="", metadata={"help": "the reward model name"})
    log_with: Optional[str] = field(default=None, metadata={"help": "use 'wandb' to log with wandb"})
    learning_rate: Optional[float] = field(default=1.41e-5, metadata={"help": "the learning rate"})
    output_max_length: Optional[int] = field(default=128, metadata={"help": "maximum length for generation"})
    mini_batch_size: Optional[int] = field(default=1, metadata={"help": "the PPO minibatch size"})
    batch_size: Optional[int] = field(default=32, metadata={"help": "the batch size"})
    ppo_epochs: Optional[int] = field(default=4, metadata={"help": "the number of ppo epochs"})
    gradient_accumulation_steps: Optional[int] = field(
        default=4, metadata={"help": "the number of gradient accumulation steps"}
    )
    adafactor: Optional[bool] = field(default=False, metadata={"help": "whether to use the adafactor optimizer"})
    early_stopping: Optional[bool] = field(default=False, metadata={"help": "whether to early stop"})
    target_kl: Optional[float] = field(default=0.1, metadata={"help": "kl target for early stopping"})
    reward_baseline: Optional[float] = field(
        default=0.0,
        metadata={"help": "a baseline value that is subtracted from the reward"},
    )
    batched_gen: Optional[bool] = field(default=False, metadata={"help": "whether to use the batched text gen"})
    save_freq: Optional[int] = field(default=None, metadata={"help": "n steps to save the model"})
    output_dir: Optional[str] = field(default="runs/", metadata={"help": "n steps to save the model"})
    seed: Optional[int] = field(default=0, metadata={"help": "the seed"})
    steps: Optional[int] = field(default=20000, metadata={"help": "number of epochs"})
    init_kl_coef: Optional[float] = field(
        default=0.2,
        metadata={"help": "Initial KL penalty coefficient (used for adaptive and linear control)"},
    )

    adap_kl_ctrl: Optional[bool] = field(default=True, metadata={"help": "Use adaptive KL control, otherwise linear"})


parser = HfArgumentParser(ScriptArguments)
script_args: ScriptArguments = parser.parse_args_into_dataclasses()[0]
reward_model_name = script_args.reward_model_name

config = PPOConfig(
    steps=script_args.steps,
    model_name=script_args.model_name,
    learning_rate=script_args.learning_rate,
    log_with=None,
    batch_size=script_args.batch_size,
    mini_batch_size=script_args.mini_batch_size,
    gradient_accumulation_steps=script_args.gradient_accumulation_steps,
    optimize_cuda_cache=True,
    early_stopping=script_args.early_stopping,
    target_kl=script_args.target_kl,
    ppo_epochs=script_args.ppo_epochs,
    seed=script_args.seed,
    init_kl_coef=script_args.init_kl_coef,
    adap_kl_ctrl=script_args.adap_kl_ctrl,
)

sent_kwargs = {
    "return_all_scores": True,
    "function_to_apply": "none",
    "batch_size": 1,
    "truncation": True,
}

tokenizer = AutoTokenizer.from_pretrained(script_args.tokenizer_name)
# GPT-2 tokenizer has a pad token, but it is not eos_token by default. We need to set it to eos_token.
# only for this model.

if getattr(tokenizer, "pad_token", None) is None:
    tokenizer.pad_token = tokenizer.eos_token


# Below is an example function to build the dataset. In our case, we use the IMDB dataset
# from the `datasets` library. One should customize this function to train the model on
# its own dataset.
def build_dataset(
    tokenizer,
    dataset_name="Dahoas/full-hh-rlhf",
):
    """
    Build dataset for training. This builds the dataset from `load_dataset`, one should
    customize this function to train the model on its own dataset.

    Args:
        dataset_name (`str`):
            The name of the dataset to be loaded.

    Returns:
        dataloader (`torch.utils.data.DataLoader`):
            The dataloader for the dataset.
    """


    ds = load_dataset("tatsu-lab/alpaca", split="train")
    ds = ds.select(range(100))
    original_columns = ds.column_names
    num_proc = 24

    def preprocess_function(examples):
        new_examples = {
            "query": [],
            "input_ids": [],
        }
        for question,input in zip(examples["instruction"],examples["input"]):
            query = question + " " + input
            tokenized_question = tokenizer(query, truncation=True)
            new_examples["query"].append(query)
            new_examples["input_ids"].append(tokenized_question["input_ids"])

        return new_examples

    ds = ds.map(
        preprocess_function,
        batched=True,
        num_proc=num_proc,
        # remove_columns=original_columns,
    )
    ds = ds.filter(lambda x: len(x["input_ids"]) < 512, batched=False)

    ds.set_format(type="torch")
    return ds


# We retrieve the dataloader by calling the `build_dataset` function.
dataset = build_dataset(tokenizer)

def collator(data):
    return dict((key, [d[key] for d in data]) for key in data[0])


# set seed before initializing value head for deterministic eval
set_seed(config.seed)

# Now let's build the model, the reference model, and the tokenizer.
current_device = Accelerator().local_process_index

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)
model = AutoModelForCausalLMWithValueHead.from_pretrained(
    config.model_name,
    load_in_8bit=True,
    device_map={"": current_device},
    peft_config=lora_config,
)

optimizer = None
if script_args.adafactor:
    optimizer = Adafactor(
        filter(lambda p: p.requires_grad, model.parameters()),
        scale_parameter=False,
        relative_step=False,
        warmup_init=False,
        lr=config.learning_rate,
    )
# We then build the PPOTrainer, passing the model, the reference model, the tokenizer
ppo_trainer = PPOTrainer(
    config,
    model,
    ref_model=None,
    tokenizer=tokenizer,
    dataset=dataset,
    data_collator=collator,
    optimizer=optimizer,
)

# We then build the sentiment analysis pipeline, passing the model name and the
# sentiment analysis pipeline arguments. Let's also make sure to set the device
# to the same device as the PPOTrainer.
device = ppo_trainer.accelerator.device
if ppo_trainer.accelerator.num_processes == 1:
    device = 0 if torch.cuda.is_available() else "cpu"  # to avoid a ` pipeline` bug
sentiment_pipe = pipeline(
    "sentiment-analysis",
    model=reward_model_name,
    device_map={"": current_device},
    model_kwargs={"load_in_8bit": True},
    tokenizer=tokenizer,
    return_token_type_ids=False,
)

# We then define the arguments to pass to the `generate` function. These arguments
# are passed to the `generate` function of the PPOTrainer, which is a wrapper around
# the `generate` function of the trained model.
generation_kwargs = {
    # "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.pad_token_id,
    "eos_token_id": 100_000,
}
output_min_length = 32
output_max_length = script_args.output_max_length
output_length_sampler = LengthSampler(output_min_length, output_max_length)

for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
    print(f"-- Epoch: {epoch} total: {config.total_ppo_epochs} --")
    if epoch >= config.total_ppo_epochs:
        break

    question_tensors = batch["input_ids"]

    response_tensors = ppo_trainer.generate(
        question_tensors,
        return_prompt=False,
        **generation_kwargs,
    )
    batch["response"] = tokenizer.batch_decode(response_tensors, skip_special_tokens=True)

    batch["query_reformat"] = []
    for query in batch["query"]:
        question =  "Question: Human: " +  query[:-5] + " Assistant:"
        batch["query_reformat"].append(question)
    # Compute sentiment score
    texts = [q + r for q, r in zip(batch["query_reformat"], batch["response"])]
    pipe_outputs = sentiment_pipe(texts, **sent_kwargs)
    rewards = [torch.tensor(output[0]["score"] - script_args.reward_baseline) for output in pipe_outputs]
    # Run PPO step
    stats = ppo_trainer.step(question_tensors, response_tensors, rewards)
    ppo_trainer.log_stats(stats, batch, rewards)

    if script_args.save_freq and epoch and epoch % script_args.save_freq == 0:
        ppo_trainer.save_pretrained(script_args.output_dir + f"step_{epoch}")
```

And script i run:
```
#!/bin/bash

SF_MODEL='/data4/share_nlp/data/luannd/pretrained_model/bloom-560m'
RW_MODEL='/data4/share_nlp/data/luannd/pretrained_model/bloom-1b1'

accelerate launch --multi_gpu --num_machines 1  \
    --num_processes 4 rl_training.py \
    --log_with=tensorboard \
    --model_name=$SF_MODEL \
    --reward_model_name=$RW_MODEL \
    --adafactor=False \
    --tokenizer_name=$SF_MODEL \
    --save_freq=100 --output_max_length=128 \
    --batch_size=1 --gradient_accumulation_steps=8 \
    --batched_gen=True --ppo_epochs=4 \
    --seed=0 --learning_rate=1.4e-5 \
    --early_stopping=True \
    --output_dir=./test_rl_bloom
```

**Comment by lvwerra** [comment] 2023-08-08 12:16
Is it possible that your batch is empty? Might be worth looking at the content and shape of `question_tensors, response_tensors, rewards`.

**Comment by Ravisutha** [comment] 2023-08-09 13:40
With #625, I did make sure that the batch wasn't empty. It seems like the list, `all_logprobs` at [line 952](https://github.com/lvwerra/trl/blob/3f1477cdc0aceb24af72638027a64bc62551c1b9/trl/trainer/ppo_trainer.py#L952) is empty and hence `torch.cat` fails.

As you point out, one reason could be that the `for` loop doesn't execute because `len(queries)` is 0. Maybe we can catch this earlier? (or maybe it's already being done somewhere else).

The other reason could be that the outputs of `logprobs_from_logits` (which makes up the items in `all_logprobs`) is `None` for some reason (which is less likely). 

If I get sometime to debug, I share my learnings here.

**Comment by tannonk** [comment] 2023-08-14 21:18
Hey,

I ran into the same issue after upgrading to v0.5.0 as well. In my case, I was able to resolve this particular error by setting `--batch_size` > `--ppo_epochs`, e.g. 8 and 4, respectively. This seemed to run fine when executing the script directly on a single GPU. @lvwerra, I'm still wrapping my head around the PPO training loop, but does this kind of constraint expected?

Following this, I immediately ran a different error during the gathering stats step when running with Accelerate. Specifically,

```
Traceback (most recent call last):
  File "llm_dqa/run_rl.py", line 10, in <module>
    main(args)
  File "llm_dqa/llm_dqa/training/trl_rlhf_pipeline/rl_training.py", line 512, in main
    stats = ppo_trainer.step(input_tensors, output_tensors, rewards)
  File "/home/user/miniconda/envs/env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "llm_dqa/src/trl/trl/trainer/ppo_trainer.py", line 790, in step
    stats = self.gather_stats(stats)
  File "llm_dqa/src/trl/trl/trainer/ppo_trainer.py", line 868, in gather_stats
    dist.all_reduce(v, dist.ReduceOp.SUM)
  File "/home/user/miniconda/envs/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda/envs/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: Tensors must be CUDA and dense
```

Looking into the stats, it seems there are indeed some non-cuda tensors in play:

```
stats: {'objective/kl': tensor(0., device='cuda:0'), 'objective/kl_dist': tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0'), 'objective/logprobs': tensor([[-11.5563, -11.9764,  -5.4583,  ..., -15.0520, -15.0520, -15.0520],
        [-11.3343, -12.1465,  -5.4880,  ...,  -1.1782,  -5.2628,  -1.0019],
        [-11.1840, -12.1794,  -5.5393,  ..., -14.9188, -14.9188, -14.9188],
        ...,
        [-10.9432, -12.0618,  -5.6076,  ..., -14.9574, -14.9574, -14.9574],
        [-11.0172, -12.0233,  -5.5254,  ..., -13.9652, -13.9652, -13.9652],
        [-11.3997, -12.0766,  -5.4817,  ..., -14.3857, -14.3857, -14.3857]],
       device='cuda:0'), 'objective/ref_logprobs': tensor([[-11.5563, -11.9764,  -5.4583,  ..., -15.0520, -15.0520, -15.0520],
        [-11.3343, -12.1465,  -5.4880,  ...,  -1.1782,  -5.2628,  -1.0019],
        [-11.1840, -12.1794,  -5.5393,  ..., -14.9188, -14.9188, -14.9188],
        ...,
        [-10.9432, -12.0618,  -5.6076,  ..., -14.9574, -14.9574, -14.9574],
        [-11.0172, -12.0233,  -5.5254,  ..., -13.9652, -13.9652, -13.9652],
        [-11.3997, -12.0766,  -5.4817,  ..., -14.3857, -14.3857, -14.3857]],
       device='cuda:0'), 'objective/kl_coef': 0.1, 'objective/entropy': tensor(239.9660, device='cuda:0'), 'ppo/mean_non_score_reward': tensor(0., device='cuda:0'), 'ppo/mean_scores': tensor(1.8063), 'ppo/std_scores': tensor(1.1983), 'tokens/queries_len_mean': 305.375, 'tokens/queries_len_std': 188.7181854248047, 'tokens/queries_dist': array([119., 569., 498., 159.,  36., 298., 349., 415.], dtype=float32), 'tokens/responses_len_mean': 82.625, 'tokens/responses_len_std': 1.0606601238250732, 'tokens/responses_dist': array([83., 83., 83., 83., 83., 83., 80., 83.], dtype=float32), 'ppo/loss/policy': tensor([-0.0071], device='cuda:0'), 'ppo/loss/value': tensor([2.6965], device='cuda:0'), 'ppo/loss/total': tensor([0.2625], device='cuda:0'), 'ppo/policy/entropy': tensor([2.9960], device='cuda:0'), 'ppo/policy/approxkl': tensor([0.0025], device='cuda:0'), 'ppo/policy/policykl': tensor([-0.0018], device='cuda:0'), 'ppo/policy/clipfrac': tensor([0.0170], device='cuda:0'), 'ppo/policy/advantages': tensor([-0.0898, -0.0898, -0.0898,  ...,  1.8248, -0.1483,  0.1668],
       device='cuda:0'), 'ppo/policy/advantages_mean': tensor([7.0419e-05], device='cuda:0'), 'ppo/policy/ratio': tensor([1.0000, 1.0000, 1.0000,  ..., 1.0358, 0.9048, 1.1788], device='cuda:0'), 'ppo/returns/mean': tensor([1.1502], device='cuda:0'), 'ppo/returns/var': tensor([0.2303], device='cuda:0'), 'ppo/val/vpred': tensor([1.0366], device='cuda:0'), 'ppo/val/error': tensor([4.1416], device='cuda:0'), 'ppo/val/clipfrac': tensor([0.4195], device='cuda:0'), 'ppo/val/mean': tensor([0.9664], device='cuda:0'), 'ppo/val/var': tensor([3.8905], device='cuda:0'), 'ppo/val/var_explained': tensor([-16.9856], device='cuda:0')}
objective/kl tensor(0., device='cuda:0')
objective/kl_dist tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
objective/logprobs tensor([[-11.5563, -11.9764,  -5.4583,  ..., -15.0520, -15.0520, -15.0520],
        [-11.3343, -12.1465,  -5.4880,  ...,  -1.1782,  -5.2628,  -1.0019],
        [-11.1840, -12.1794,  -5.5393,  ..., -14.9188, -14.9188, -14.9188],
        ...,
        [-10.9432, -12.0618,  -5.6076,  ..., -14.9574, -14.9574, -14.9574],
        [-11.0172, -12.0233,  -5.5254,  ..., -13.9652, -13.9652, -13.9652],
        [-11.3997, -12.0766,  -5.4817,  ..., -14.3857, -14.3857, -14.3857]],
       device='cuda:0')
objective/ref_logprobs tensor([[-11.5563, -11.9764,  -5.4583,  ..., -15.0520, -15.0520, -15.0520],
        [-11.3343, -12.1465,  -5.4880,  ...,  -1.1782,  -5.2628,  -1.0019],
        [-11.1840, -12.1794,  -5.5393,  ..., -14.9188, -14.9188, -14.9188],
        ...,
        [-10.9432, -12.0618,  -5.6076,  ..., -14.9574, -14.9574, -14.9574],
        [-11.0172, -12.0233,  -5.5254,  ..., -13.9652, -13.9652, -13.9652],
        [-11.3997, -12.0766,  -5.4817,  ..., -14.3857, -14.3857, -14.3857]],
       device='cuda:0')
objective/kl_coef 0.1
objective/entropy tensor(239.9660, device='cuda:0')
ppo/mean_non_score_reward tensor(0., device='cuda:0')
ppo/mean_scores tensor(1.8063)
```

This probably requires its own issue, so I'll open a new one if I don't find an obvious fix.

**Comment by lvwerra** [comment] 2023-08-16 08:42
I am closing this issue in favour of #648 to track progress on fixing the bug.

**Closed by lvwerra** 2023-08-16 08:42 UTC

**Comment by a1149811425** [comment] 2024-05-13 02:07
I also encountered this bug. It occurs because the data members that need to be concatenated are all empty, making it impossible to retrieve the data. I resolved this issue by adding a condition during processing: if no matching members are found, they are replaced with empty tensor members.
