### ISSUE TITLE
KTO hangs when using DeepSpeed

### ISSUE THREAD

**Issue by dblakely** [huggingface/trl#1342] opened 2024-02-20 22:27 UTC
Hey there,

I've run into an issue where KTO training hangs when I run it using DeepSpeed - it runs for a couple steps and then I first get loss values and reward values of 0 or NaN:

```
{'loss': 0.5, 'learning_rate': 9.99e-05, 'rewards/chosen': 0.0, 'rewards/rejected': 0.0, 'rewards/accuracies': 0.0, 'rewards/margins': 0.0, 'logps/rejected': -202.1331024169922, 'logps/chosen': -336.5407409667969, 'logits/rejected': -116.42853546142578, 'logits/chosen': -97.47003173828125, 'kl': 0.0, 'epoch': 0.0}                             
{'loss': 0.6534, 'learning_rate': 9.98e-05, 'rewards/chosen': -0.4333324432373047, 'rewards/rejected': nan, 'rewards/accuracies': 0.0, 'rewards/margins': nan, 'logps/rejected': nan, 'logps/chosen': -61.395660400390625, 'logits/rejected': nan, 'logits/chosen': -104.99060821533203, 'kl': 0.0, 'epoch': 0.01}                                                
{'loss': 0.0, 'learning_rate': 9.970000000000001e-05, 'rewards/chosen': -0.6865890622138977, 'rewards/rejected': -0.010017603635787964, 'rewards/accuracies': 0.0, 'rewards/margins': -0.6765714883804321, 'logps/rejected': -70.71566772460938, 'logps/chosen': -198.41256713867188, 'logits/rejected': -107.62744140625, 'logits/chosen': -102.08055114746094, 'kl': nan, 'epoch': 0.01}
{'loss': 0.0, 'learning_rate': 9.960000000000001e-05, 'rewards/chosen': nan, 'rewards/rejected': nan, 'rewards/accuracies': 0.0, 'rewards/margins': nan, 'logps/rejected': nan, 'logps/chosen': nan, 'logits/rejected': nan, 'logits/chosen': nan, 'kl': nan, 'epoch': 0.02}
{'loss': 0.0, 'learning_rate': 9.95e-05, 'rewards/chosen': nan, 'rewards/rejected': nan, 'rewards/accuracies': 0.0, 'rewards/margins': nan, 'logps/rejected': nan, 'logps/chosen': nan, 'logits/rejected': nan, 'logits/chosen': nan, 'kl': nan, 'epoch': 0.02}
```

and then it hangs. When I command C to kill it, it just shows the processing waiting on PID:

```
Traceback (most recent call last):
  File "/home/fsuser/.local/bin/deepspeed", line 6, in <module>
    main()
  File "/home/fsuser/.local/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 584, in main
    result.wait()
  File "/usr/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

When I do not use DeepSpeed, everything looks fine.

**To Reproduce**

- Run [examples/kto.py](https://github.com/huggingface/trl/blob/main/examples/scripts/kto.py) script
- Use these args:

```bash
export CUDA_VISIBLE_DEVICES=0,1,2,3

deepspeed --master_port 6000 kto.py \
    --model_name_or_path "gpt2" \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --learning_rate 1e-4 \
    --max_steps 1000 \
    --report_to "wandb" \
    --gradient_checkpointing True  \
    --output_dir "./test" \
    --evaluation_strategy "steps" \
    --eval_steps 10 \
    --logging_first_step True \
    --logging_steps 1 \
    --beta 0.1 \
    --deepspeed ds_config.json \
```

- `ds_config.json` is:

```json
{
    "fp16": {
        "enabled": "auto"
    },
    "bf16": {
        "enabled": "auto"
    },
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients": true,
        "round_robin_gradients": true,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "steps_per_print": 500,
    "wall_clock_breakdown": false
}
```

However, it doesn't seem to matter which DS stage I use and whether I use CPU offloading -- I'm run into the same issue.

**Versions**

```txt
trl==0.7.12.dev0
transformers==4.36.2
accelerate==0.27.2
deepspeed==0.13.2
torch==2.0.0+cu118
```

Tagging @kashif for now since he authored the `KTOTrainer`. Thanks in advance

**Comment by Qubitium** [comment] 2024-02-20 22:33
What gpus are you using? Deepspeed will use nccl/p2p but if your gpu (4090 for example) doesnt support it, it will hang.

**Comment by dblakely** [comment] 2024-02-20 23:10
Hey @Qubitium, I'm using A6000s. I also just tried running it on a pair of A100s and hit the same problem

**Comment by kashif** [comment] 2024-02-21 07:16
thanks @dblakely  to confirm the cause of the issue, can you try running with a larger batch size, e.g. 8 or 16 ?

**Comment by kashif** [comment] 2024-02-21 15:08
so as suspected @dblakely the issue i think is that with smaller batch sizes there aren't enough KL-term completions and/or kto completions terms to then calculate the respective losses... 

hmm, i thought I also increased the eval batch size too... so not sure why the eval loss terms are nans...

**Comment by dblakely** [comment] 2024-02-21 15:44
Thanks for the info @kashif. So that suggests the issue isn't really DeepSpeed at all? Odd that it seems to work without DeepSpeed when the batch size is small

**Comment by kashif** [comment] 2024-02-23 15:29
@Muennighoff  can you try with larger train and eval batch sizes, i suspect the issue is that deepspeed is not as forgiving with nans in the loss as accelerate it...

**Comment by kawine** [comment] 2024-02-25 04:31
even if you hotfix this with a larger batch size, the training will be worse because of the higher variance in loss estimates (e.g., the KL term could be estimated with as little as one (x,y') pair, which could be way off)

@dblakely I'm working on a PR to fix this. will comment here once it's up and merged

**Comment by kawine** [comment] 2024-02-28 11:14
PR opened here: https://github.com/huggingface/trl/pull/1380

we've tried the KTOTrainer at some small scales with deepspeed and it should work with these new changes

**Comment by dblakely** [comment] 2024-02-29 21:17
Hey @kawine thanks for doing this so quickly.

I tried to reproduce with the same args as in the OP and I'm no longer seeing NaN values for the loss. However, I see `rewards/chosen`, `rewards/rejected`, `logps/rejected`, `logps/chosen`, `logits/chosen`, and `logits/rejected` are often NaN. Is that expected?

**Comment by kawine** [comment] 2024-02-29 23:29
@dblakely that happens because each microbatch contains a random mix of positive/negative examples, so if by chance the microbatch contains all negative/all positive, the rejected/chosen rewards can be NaN respectively

It happens quite frequently in the current implementation because the reported stats are only from the main process (i.e., from one microbatch, not the whole batch). Gathering these metrics across all microbatches should reduce the odds of a NaN, but it also causes the hanging issue in deepseed

so the NaNs should *not* affect the quality of your training, but nonetheless I'll see if I can get rid of them

**Comment by dblakely** [comment] 2024-03-01 17:00
Thanks for looking into that. I reran the example script for an epoch and I no longer see any NaN values

Seems like everything is working fine now, closing this issue. Thanks a lot

**Comment by hbin0701** [comment] 2024-03-05 12:15
Hello! is this fixed? I'm experiencing similar issue, yet even before the first step completes. (i'm using accelerate + deepseed) i.e.

It hangs here:

from `get_batch_loss_metrics()` in `KTOTrainer`:
```       
        print("this runs!") 
        print(f"CHOSEN LOGPS SHAPE: {policy_chosen_logps.shape}\n")

        mean_chosen_reward = self.accelerator.gather(chosen_rewards.detach()).nanmean().nan_to_num(0)
        mean_rejected_reward = self.accelerator.gather(rejected_rewards.detach()).nanmean().nan_to_num(0)
        mean_margin = mean_chosen_reward - mean_rejected_reward
        mean_logps_chosen = self.accelerator.gather(policy_chosen_logps.detach()).nanmean().nan_to_num(0)
        mean_logps_rejected = self.accelerator.gather(policy_rejected_logps.detach()).nanmean().nan_to_num(0)
        
        print("this doesn't")
```

I'm using 2xA100 (also tried with 4 and 8), and I'm using batch size of 8. Interestingly, I get:
        
CHOSEN LOGPS SHAPE: torch.Size([1])
CHOSEN LOGPS SHAPE: torch.Size([5])

Could this be a reason why it hangs? and how can I fix it? Thanks in advnace!

**Comment by dblakely** [comment] 2024-03-05 19:31
Actually, I closed this prematurely - the NaN loss issue _is_ fixed but I'm still finding that KTO training often hangs when I use DeepSpeed

**Comment by kashif** [comment] 2024-03-05 19:35
I see... so you think there is some deadlock?

**Comment by kawine** [comment] 2024-03-05 20:52
@dblakely does it hang in the beginning or somewhere in the middle of training?

**Comment by hbin0701** [comment] 2024-03-05 22:46
For me, it hangs in the beginning :(

**Comment by Muennighoff** [comment] 2024-03-05 22:55
> For me, it hangs in the beginning :(

Can you share the config & script you're using? My issues have been resolved with DeepSpeed; I think FSDP is still buggy but that's for TRL in general see https://github.com/huggingface/trl/issues/1147

**Comment by hbin0701** [comment] 2024-03-05 23:05
I'm running ```ACCELERATE_LOG_LEVEL=info accelerate launch --config_file /workspace/sdpo/scripts/math/dpo/deepspeed_zero3.yaml dpo/run_kto.py /workspace/sdpo/scripts/math/dpo/kto_config.yaml```

where `kto_config.yaml` is
```
# Model arguments
model_name_or_path: /workspace/models/gsm8k/deepseek_brft
run_name: GSM8K_deepseek_kto

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12
train_data_file: /workspace/sdpo/data/kto/deepseek_kto_dataset_DPO.json
test_data_file: /workspace/sdpo/data/kto/deepseek_kto_dataset_DPO.json

# KTOTrainer argument
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: false
hub_model_id: zephyr-7b-dpo-full
learning_rate: 1.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 384
max_prompt_length: 256
num_train_epochs: 3
optim: rmsprop
output_dir: /workspace/models/deepseek_kto_gsm8k_DPO
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "epoch"
save_only_model: true
save_total_limit: 3
seed: 42
warmup_ratio: 0.1 
```

with `deepspeed_zero3.yaml`:

```
compute_environment: LOCAL_MACHINE
main_process_port: 32899
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

and `run_kto.py`
```
import logging
import sys
import wandb
import torch
import transformers
from transformers import AutoModelForCausalLM, set_seed, LlamaTokenizer, AutoTokenizer
from accelerate import Accelerator

import sys
sys.path.append("/workspace/sdpo/dpo")

from alignment import (
    DataArguments,
    DPOConfig,
    H4ArgumentParser,
    ModelArguments,
    apply_chat_template,
    get_datasets,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
    get_tokenizer,
    is_adapter_model,
)


from peft import PeftConfig, PeftModel
# from custom_trainer import DPOTrainer, KTOTrainer, KTOConfig
from prepare_dataset import get_dataset
from trls.trl.trainer import KTOTrainer, KTOConfig # where trls is the github repo for trl
# from step_prepare_dataset import get_dataset
import os

os.environ["WANDB_API_KEY"] = "49e3bf1d97a7148ae772622876fd9ac8b08ce60e"
os.environ["WANDB_ENTITY"] ="hbin0701"
os.environ["WANDB_PROJECT"] ="DPO"

logger = logging.getLogger(__name__)


def main():
    parser = H4ArgumentParser((ModelArguments, DataArguments, KTOConfig))
    model_args, data_args, training_args = parser.parse()

    #######
    # Setup
    #######
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[logging.StreamHandler(sys.stdout)],
    )
    log_level = training_args.get_process_log_level()
    logger.setLevel(log_level)
    transformers.utils.logging.set_verbosity(log_level)
    transformers.utils.logging.enable_default_handler()
    transformers.utils.logging.enable_explicit_format()

    # Log on each process the small summary:
    logger.info(f"Model parameters {model_args}")
    logger.info(f"Data parameters {data_args}")
    logger.info(f"Training/evaluation parameters {training_args}")

    # Set seed for reproducibility
    set_seed(training_args.seed)

    # Increase distributed timeout to 3h to enable push to Hub to complete
    accelerator = Accelerator()
    tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)

    # there should be "train" and "test", with column anme "text_prompt", "text_chosen", "text_rejected".
    # raw_datasets = get_dataset(data_args.train_data_file, data_args.test_data_file)
    import json
    from datasets import Dataset

    data = json.load(open(data_args.train_data_file))
    test_set = Dataset.from_dict({k: v[:100] for k, v in data.items()})
    train_set = Dataset.from_dict({k: v[:900] for k, v in data.items()}) # temporary
    # shuffle train_set

    torch_dtype = (
        model_args.torch_dtype if model_args.torch_dtype in ["auto", None] else getattr(torch, model_args.torch_dtype)
    )

    model_kwargs = dict(
        revision=model_args.model_revision,
        trust_remote_code=model_args.trust_remote_code,
        use_flash_attention_2=model_args.use_flash_attention_2,
        torch_dtype=torch_dtype,
        use_cache=False if training_args.gradient_checkpointing else True,
        device_map=get_kbit_device_map(),
        quantization_config=get_quantization_config(model_args),
    )

    model = AutoModelForCausalLM.from_pretrained(model_args.model_name_or_path, **model_kwargs).to(torch.bfloat16)
    ref_model = AutoModelForCausalLM.from_pretrained(model_args.model_name_or_path, **model_kwargs).to(torch.bfloat16)

    # if model_args.use_peft is True:
    #     ref_model = None
    #     ref_model_kwargs = None

    #########################
    # Instantiate DPO trainer
    #########################
    # training_args.model_init_kwargs = model_kwargs
    # training_args.ref_model_init_kwargs = ref_model_kwargs

    kto_trainer = KTOTrainer(
        model,
        ref_model,
        args=training_args,
        train_dataset= train_set,
        eval_dataset=test_set,
        tokenizer=tokenizer,
        peft_config=get_peft_config(model_args),
    )

    ###############
    # Training loop
    ###############
    train_result = kto_trainer.train()
    metrics = train_result.metrics
    max_train_samples = (
        data_args.max_train_samples if data_args.max_train_samples is not None else len(train_set)
    )
    metrics["train_samples"] = min(max_train_samples, len(train_set))
    kto_trainer.log_metrics("train", metrics)
    kto_trainer.save_metrics("train", metrics)
    kto_trainer.save_state()

    logger.info("*** Training complete ***")

    # Evaluate
    if training_args.do_eval:
        logger.info("*** Evaluate ***")
        metrics = kto_trainer.evaluate()
        max_eval_samples = (
            data_args.max_eval_samples if data_args.max_eval_samples is not None else len(test_set)
        )
        metrics["eval_samples"] = min(max_eval_samples, len(kto_trainer["test"]))
        kto_trainer.log_metrics("eval", metrics)
        kto_trainer.save_metrics("eval", metrics)

    # Save model and create model card
    kto_trainer.save_model(training_args.output_dir)

    # Save everything else on main process
    if accelerator.is_main_process:
        kwargs = {
            "finetuned_from": model_args.model_name_or_path,
            "dataset": list(data_args.dataset_mixer.keys()),
            "dataset_tags": list(data_args.dataset_mixer.keys()),
            "tags": ["alignment-handbook"],
        }
        kto_trainer.create_model_card(**kwargs)
        # Restore k,v cache for fast inference
        kto_trainer.model.config.use_cache = True
        kto_trainer.model.config.save_pretrained(training_args.output_dir)
        if training_args.push_to_hub is True:
            kto_trainer.push_to_hub()

    # Ensure we don't timeout on model save / push to Hub
    logger.info("*** Waiting for all processes to finish ***")
    accelerator.wait_for_everyone()

    logger.info("*** Run complete! ***")


if __name__ == "__main__":
    main()
```


I use the similar script for DPOTrainer, which works fine. One thing that I noticed is that KTOTrainer uses significantly lower memory than DPO does. Is this intended to be as such? Thank you in advance! Meantime, I'll try again with your suggestions!

**Comment by kawine** [comment] 2024-03-05 23:20
This might be because when there are only positive/negative examples in a microbatch, the `policy_chosen_logps` or `policy_rejected_logps` is changed from an empty tensor to `[torch.nan]` just before being gathered, since empty tensors cause hanging in accelerate for some reason.

However, if the tensors are empty on one machine when gather() is called on another, we're back to square one --> hanging.

@hbin0701 Can you verify this by commenting out the following lines:

```
 mean_logps_chosen = self.accelerator.gather(policy_chosen_logps.detach()).nanmean().nan_to_num(0)
mean_logps_rejected = self.accelerator.gather(policy_rejected_logps.detach()).nanmean().nan_to_num(0)
```

and 

```
metrics[f"{prefix}logps/rejected"] = mean_logps_chosen.cpu()
metrics[f"{prefix}logps/chosen"] = mean_logps_rejected.cpu()
```

**Comment by hbin0701** [comment] 2024-03-05 23:59
Hmm. seems like there's some problem with the rejected_rewards. It still hangs. I added some print statements for debugging.

```
       losses, chosen_rewards, rejected_rewards, kl = self.kto_loss(
            policy_chosen_logps,
            policy_rejected_logps,
            policy_KL_logps,
            reference_chosen_logps,
            reference_rejected_logps,
            reference_KL_logps,
        )

        print("Running here [1]!")
        # lists can't be empty -- if they are, then accelerate.gather will hang
        if policy_chosen_logps.shape[0] == 0:
            policy_chosen_logps = torch.Tensor([torch.nan]).to(self.accelerator.device)

        if policy_rejected_logps.shape[0] == 0:
            policy_rejected_logps = torch.Tensor([torch.nan]).to(self.accelerator.device)

        print(f"Running here [2]! <{chosen_rewards}>\n\n") # Often hangs here
        mean_chosen_reward = self.accelerator.gather(chosen_rewards.detach()).nanmean().nan_to_num(0)
        print("\nFinished Running [2]!")

        print(f"Running here [3]! <{rejected_rewards}>\n\n") # or here
        mean_rejected_reward = self.accelerator.gather(rejected_rewards.detach()).nanmean().nan_to_num(0)

        print("Running here [4]!")
        mean_margin = mean_chosen_reward - mean_rejected_reward
        # mean_logps_chosen = self.accelerator.gather(policy_chosen_logps.detach()).nanmean().nan_to_num(0)
        # mean_logps_rejected = self.accelerator.gather(policy_rejected_logps.detach()).nanmean().nan_to_num(0)

        prefix = "eval_" if train_eval == "eval" else ""
        metrics[f"{prefix}rewards/chosen"] = mean_chosen_reward.cpu()
        metrics[f"{prefix}rewards/rejected"] = mean_rejected_reward.cpu()
        print("Running here [5]!")
        metrics[f"{prefix}rewards/margins"] = mean_margin.cpu()
        metrics[f"{prefix}kl"] = kl.item()  # has already been gathered in kto_loss
        print("Running here [6]!")


```
results as following:
```
Running here [1]!
Running here [1]!Running here [2]! <tensor([0., 0., 0., 0., 0., 0.], device='cuda:5')>
Running here [2]! <tensor([0.], device='cuda:0')>
Finished Running [2]!
Finished Running [2]!
Running here [1]!
Running here [2]! <tensor([0., 0., 0., 0., 0.], device='cuda:4')>
Finished Running [2]!
Running here [1]!
Running here [2]! <tensor([0., 0.], device='cuda:7')>
Finished Running [2]!
Running here [1]!
Running here [1]!
Running here [2]! <tensor([0., 0.], device='cuda:2')>
Running here [2]! <tensor([0., 0., 0., 0., 0.], device='cuda:1')>
Running here [1]!
Running here [1]!
Finished Running [2]!
Running here [2]! <tensor([0., 0., 0., 0., 0.], device='cuda:6')>
Running here [2]! <tensor([0., 0., 0.], device='cuda:3')>
Finished Running [2]!
Finished Running [2]!
Finished Running [2]!

```

**Comment by kawine** [comment] 2024-03-06 03:00
hmm so this appears to happen whenever you try to accelerate.gather on any tensor that is not a 1x1 tensor, which is weird because torch.gather doesn't have this requirement. whenever you have a tensor that is not 1x1, accelerate may or may not hang. i've patched this problem by just taking the nanmean before the gather.

@hbin0701 can you see if the code on my fork works for you? https://github.com/kawine/trl

the only functions i changed were kto_loss and get_batch_loss_metrics in case you just want to copy-paste

**Comment by dblakely** [comment] 2024-03-07 13:01
Hey @kawine, so far your branch seems to work for me

**Comment by hbin0701** [comment] 2024-03-08 05:20
Hey @kawine . Sorry for the late reply.
With your newest file: "https://github.com/kawine/trl/blob/8f9fdfe12e5fff3c8af3a023b16aff69c4f23bdc/trl/trainer/kto_trainer.py",
my code now runs without any error. While I don't see any hanging in the middle (yet) as @dblakely experienced, if I find any, I'll come back to report.  Thank you very much for the help! 👍

**Closed** 2024-04-01 16:16 UTC
