### ISSUE TITLE
IndexError: Invalid key: 28 is out of bounds for size 0

### ISSUE THREAD

**Issue by serino28** [huggingface/trl#519] opened 2023-07-14 15:20 UTC
```
IndexError                                Traceback (most recent call last)
[<ipython-input-17-3435b262f1ae>](https://localhost:8080/#) in <cell line: 1>()
----> 1 trainer.train()

11 frames
[/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py](https://localhost:8080/#) in _check_valid_index_key(key, size)
    524     if isinstance(key, int):
    525         if (key < 0 and key + size < 0) or (key >= size):
--> 526             raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
    527         return
    528     elif isinstance(key, slice):
```

IndexError: Invalid key: 28 is out of bounds for size 0

despite the fact that I have downloaded the latest version of the library, I still get this error. 
Can someone please help me?

**Comment by younesbelkada** [comment] 2023-07-14 15:55
Hi @serino28 
Thanks for the issue, can you provide more details on how you get the issue, ideally with a reproducible handy snippet to better help you?

**Comment by serino28** [comment] 2023-07-14 16:03
> Hi @serino28 Thanks for the issue, can you provide more details on how you get the issue, ideally with a reproducible handy snippet to better help you?
Sure, I am trying to fine-tune a falcon 7b-instruct using my own dataset. 
When I try to call trainer.train() I get this error. 
I attach the relevant code:

`from peft import LoraConfig

lora_alpha = 16
lora_dropout = 0.1
lora_r = 64

peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="RWForCausalLM",
    target_modules=[
        "query_key_value",
        "dense",
        "dense_h_to_4h",
        "dense_4h_to_h",
    ]
)

from transformers import TrainingArguments

output_dir = "./results_prova2"
per_device_train_batch_size = 4
gradient_accumulation_steps = 4
optim = "paged_adamw_32bit"
save_steps = 10
logging_steps = 10
learning_rate = 2e-4
max_grad_norm = 0.3
max_steps = 3
warmup_ratio = 0.03
lr_scheduler_type = "constant"

training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=True,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=True,
    lr_scheduler_type=lr_scheduler_type,
)

from trl import SFTTrainer

max_seq_length = 512

trainer = SFTTrainer(
    model=model,
    train_dataset=data,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
)

for name, module in trainer.model.named_modules():
    if "norm" in name:
        module = module.to(torch.float32)

trainer.train()
`

**Comment by younesbelkada** [comment] 2023-08-17 08:51
HI @serino28 
Do you still face the same issue? I think the problem is on the way you create the dataset, can you share how you create your dataset?

**Comment by younesbelkada** [comment] 2023-09-11 08:20
Closing, feel free to re-open if you need help!

**Closed** 2023-09-11 08:20 UTC
