### ISSUE TITLE
Issue with FSDP on DPO trainer: ref_model was not placed on cuda

### ISSUE THREAD

**Issue by hanyin88** [huggingface/trl#1147] opened 2023-12-26 13:34 UTC
Hey there,

There appears to be an issue when using accelerator FSDP with DPO trainer, where it says tensors are not on the same device. 

After quite some testing, I realized the issue is that ref_model was not moved to Cuda. It seems with this line in DPO.trainer:`self.ref_model = self.accelerator.prepare_model(self.ref_model, evaluation_mode=True)`, ref_model was not placed on cuda. As a matter of fact, after dpo_trainer initiation and before dpo_trainer.train(), both dpo_trainer.model.device and dpo_trainer.ref_model.device are "CPU" as expected. However later during training, after `model = FSDP(model, **kwargs) `in acclerator.py, the main model is moved to cuda, but ref_model was never moved. 

Appreciate any guidance. 

I attached detailed error message below:

"
File "/data/hanyinw2/dc_summary/RLHF/try_DPO.py", line 294, in DPO
    dpo_trainer.train()
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/transformers/trainer.py", line 2725, in training_step
    loss = self.compute_loss(model, inputs)
  File "/srv/local/data/hanyinw2/trl/trl/trainer/dpo_trainer.py", line 975, in compute_loss
    loss, metrics = self.get_batch_loss_metrics(model, inputs, train_eval="train")
  File "/srv/local/data/hanyinw2/trl/trl/trainer/dpo_trainer.py", line 942, in get_batch_loss_metrics
    ) = self.concatenated_forward(self.ref_model, batch)
  File "/srv/local/data/hanyinw2/trl/trl/trainer/dpo_trainer.py", line 884, in concatenated_forward
    all_logits = model(
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/accelerate/utils/operations.py", line 659, in forward
    return model_forward(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/accelerate/utils/operations.py", line 647, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1034, in forward
    outputs = self.model(
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 879, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/data/hanyinw2/dc_summary_env/lib/python3.9/site-packages/torch/nn/functional.py", line 2238, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:2! (when checking argument for argument index in method wrapper_CUDA__index_select)
"

**Comment by agokrani** [comment] 2024-01-01 05:45
I am having similar error
 File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1864, in _inner_training_loop
    tr_loss += tr_loss_step
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by AjayP13** [comment] 2024-01-01 18:13
This is currently an issue. I also opened #1160 related to this, which even after you get FSDP working, the metrics logging causes an error if using Early Stopping Callback.

**Comment by agokrani** [comment] 2024-01-02 08:25
Hi @AjayP13,

But were you able to get FSDP working? I tried forcing the logps and loss to move to device but in my case, I didn't see the problem solving, and I don't see the code in your commit as well to make FSDP work. Do you have any suggestions to make it work?

**Comment by Yifan-Song793** [comment] 2024-01-14 14:02
Just set the `evaluation_mode=False` for device preparation of ref_model in DPOTrainer: https://github.com/huggingface/trl/blob/fa074e6a1565fb6dc4dc0035805a763c64b33c3d/trl/trainer/dpo_trainer.py#L395C19-L395C19
If the evaluation_mode is set to be True, the prepare_model function in accelerate will not set the FSDP on the model. See https://github.com/huggingface/accelerate/blob/31fd2b1ad6b9c1cd1480568399a311b3caaf62dc/src/accelerate/accelerator.py#L1341

**Comment by younesbelkada** [comment] 2024-01-17 13:37
Hi everyone ! 
#1160 being merged I think that FSDP should now work with DPO - @AjayP13 Can you share with me a small snippet to showcase how to use FSDP + DPO? I want to design a small GPU test for it now that we added GPU tests in TRL https://github.com/huggingface/trl/pull/1218

**Comment by agokrani** [comment] 2024-01-17 15:44
Hi @younesbelkada, 

I am still getting the same error 
Stopping app - uncaught exception raised locally: RuntimeError('Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!')

I have already tried what @Yifan-Song793 suggested, it doesn't seem to work in my case. I tried couple of other things as well. Not really sure where this error is coming from.

**Comment by AjayP13** [comment] 2024-01-17 16:50
@younesbelkada Unfortunately, #1160 alone will not fix FSDP + DPO. 

The issue is slightly more complicated, especially when using `precompute_ref_log_probs`, I was able to work around the issue in my client code by doing some hack-y things, that I don't think can be easily PR'ed into TRL.

The issue is the HuggingFace `transformers.Trainer` class prepares the models for `accelerate` in the `inner_training_loop`. However, they must be prepared much earlier for the models to be prepared by the time  the code for `precompute_ref_log_probs` runs.

I solved this by preparing the models myself before training, and then monkey-patching `trainer.accelerator.prepare_model` to be a no-op so that `transformers.Trainer` will not be able to prepare them a second time.

1. **Step 1**: Instantiate `trainer = DPOTrainer(...)`
2. **Step 2**: Hacky Manual `prepare()` and Monkey Patch: 
      ```python
      prepared_model = trainer._wrap_model(
          trainer.model, training=True, dataloader=None
      )
      if hasattr(trainer.lr_scheduler, "step"):
          prepared_model, trainer.optimizer = trainer.accelerator.prepare(
              prepared_model, trainer.optimizer
          )
      else:
          (
              prepared_model,
              trainer.optimizer,
              trainer.lr_scheduler,
          ) = trainer.accelerator.prepare(
              prepared_model, trainer.optimizer, trainer.lr_scheduler
          )
      trainer.model_wrapped = prepared_model
      if trainer.is_fsdp_enabled:
          trainer.model = prepared_model
      if trainer.ref_model is not None:
          trainer.ref_model = trainer.accelerator.prepare_model(trainer.ref_model)

      trainer.accelerator.prepare_model = lambda model, *args, **kwargs: model # Monkey-patch prepare_model a no-op , since we have manually prepared the models
      ```
5. **Step 3**: - Run `trainer.train(...)`


In order for this to be fixed, I believe `DPOTrainer` needs to take charge of preparing both the `model` and `ref_model` in its `__init__` and there would need to be some sort of change in `transformers.Trainer` to add an option to disable it from running any `accelerator.prepare()` on models when the models have already been prepared before handing them to `transformers.Trainer`.

I don't have bandwidth to make this PR, but hopefully this outlines the issue for a future fix.

**Comment by hanyin88** [comment] 2024-01-22 02:37
Thank you soooo much @AjayP13 ! I can confirm adding your suggested codes before trainer.train() works, and other suggested including with the latest PR won't work for me.

@AjayP13, would you mind if i ask about your FSDP config and the codes for saving the trained model? I run into some issues in saving the model after training, likely related to the way accelerator prepares model as seen in other post. Deeply appreciate the kind help!

**Comment by AjayP13** [comment] 2024-01-22 20:18
Hi @hanyin88, I'm happy to help offline, you can find my email on my profile.

**Comment by AjayP13** [comment] 2024-02-05 22:42
The fix I described earlier is implemented in a higher-level open source library around training models (that uses HuggingFace TRL as a dependency) we are building for LLM researchers at the University of Pennsylvania called [DataDreamer](https://datadreamer.dev/docs/latest/index.html): 

https://github.com/datadreamer-dev/DataDreamer

You can do DPO + PEFT + FSDP with this library (there are some examples on the website). Also, it may serve as a nice reference implementation for a fix for FSDP + DPO in TRL in the future (the source code is available).

**Closed** 2024-03-10 15:05 UTC
Labels: DPO

**Comment by benjamin-marie** [comment] 2024-11-21 20:27
Amazing! I ran into the same issue and this patch still works!
