### ISSUE TITLE
AttributeError: 'PPOv2Trainer' object has no attribute 'deepspeed'

### ISSUE THREAD

**Issue by suanflower** [huggingface/trl#2029] opened 2024-09-06 09:37 UTC
### System Info

pip install transformers==4.43.4

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

AttributeError: 'PPOv2Trainer' object has no attribute 'deepspeed'

### Expected behavior

AttributeError: 'PPOv2Trainer' object has no attribute 'deepspeed'

**Comment by PauliusSasnauskas** [comment] 2024-09-06 11:05
Duplicate of #2025

**Comment by real-ljs** [comment] 2024-09-13 15:00
have the same question as you

**Comment by qgallouedec** [comment] 2024-09-13 15:54
Closing in favor of #2025

**Closed** 2024-09-13 15:54 UTC
Labels: bug, duplicate
