### ISSUE TITLE
questions about DPO

### ISSUE THREAD

**Issue by skepsun** [huggingface/trl#621] opened 2023-08-07 09:12 UTC
1. I tried to run dpo.py with 7b model but still encounter OOM error on 7xA800(80G). So how much memory is necessary for this?
2. dpo.py is a bit simple, I tried to add support for deepspeed but still got OOM error. Maybe we should have a complete guideline or example about dpo on llama or other LLMs larger than gpt2?

**Comment by lvwerra** [comment] 2023-08-08 08:10
We usually use PEFT when memory is an issue - it works well even with 7b/15b or larger models!

**Comment by laosuan** [comment] 2023-08-09 02:10
could you add a complete example of generate.py? The output of the model I trained by loading dpo.py is very strange.

**Comment by lvwerra** [comment] 2023-08-09 10:21
Which `generate.py` are you referring to?

**Comment by laosuan** [comment] 2023-08-09 12:04
> Which `generate.py` are you referring to?

## Running the model

We can load the DPO-trained LoRA adaptors which were saved by the DPO training step and load them via:

```py
from peft import AutoPeftModelForCausalLM


model = AutoPeftModelForCausalLM.from_pretrained(
    "dpo/final_checkpoint",
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,
    load_in_4bit=True,
)

model.generate(...)
```

**Comment by lvwerra** [comment] 2023-08-10 08:20
This would be a full example:
```python
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

model_name = "dpo/final_checkpoint"

model = AutoPeftModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,
    load_in_4bit=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

inputs = tokenizer.encode("Question: Please write a function in Python that performs bubble sort.\n\nAnswer:", return_tensors="pt")
outputs = model.generate(inputs)
print(tokenizer.decode(outputs[0]))

**Comment by laosuan** [comment] 2023-08-10 12:54
> 
when I run the example,
Traceback (most recent call last):
  File "/home/mike/trl/examples/research_projects/stack_llama_2/scripts/generate.py", line 7, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/peft/auto.py", line 101, in from_pretrained
    base_model = target_class.from_pretrained(base_model_path, **kwargs)
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/utils/hub.py", line 433, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

I think there should be a problem saving dpo checkpoint.
"base_model_name_or_path": null   from
/home/mike/trl/examples/research_projects/stack_llama_2/scripts/dpo/final_checkpoint/adapter_config.json:
```
{
  "auto_mapping": null,
  "base_model_name_or_path": null,
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 16,
  "lora_dropout": 0.05,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 8,
  "revision": null,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "out_proj",
    "fc_in",
    "fc_out",
    "wte"
  ],
  "task_type": "CAUSAL_LM"
}
```

**Comment by lvwerra** [comment] 2023-08-11 08:44
Seems like the model can't be found in the folder you specified. Can you double check that the folder is the correct one and contains the model?

**Comment by nubs4dayz** [comment] 2023-08-22 13:40
> > 
> 
> when I run the example, Traceback (most recent call last): File "/home/mike/trl/examples/research_projects/stack_llama_2/scripts/generate.py", line 7, in model = AutoPeftModelForCausalLM.from_pretrained( File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/peft/auto.py", line 101, in from_pretrained base_model = target_class.from_pretrained(base_model_path, **kwargs) File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained config, kwargs = AutoConfig.from_pretrained( File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs) File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs) File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict resolved_config_file = cached_file( File "/home/mike/anaconda3/envs/trl/lib/python3.10/site-packages/transformers/utils/hub.py", line 433, in cached_file raise EnvironmentError( OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models' If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
> 
> I think there should be a problem when saving dpo checkpoint. "base_model_name_or_path": null from /home/mike/trl/examples/research_projects/stack_llama_2/scripts/dpo/final_checkpoint/adapter_config.json:
> 
> ```
> {
>   "auto_mapping": null,
>   "base_model_name_or_path": null,
>   "bias": "none",
>   "fan_in_fan_out": false,
>   "inference_mode": true,
>   "init_lora_weights": true,
>   "layers_pattern": null,
>   "layers_to_transform": null,
>   "lora_alpha": 16,
>   "lora_dropout": 0.05,
>   "modules_to_save": null,
>   "peft_type": "LORA",
>   "r": 8,
>   "revision": null,
>   "target_modules": [
>     "q_proj",
>     "v_proj",
>     "k_proj",
>     "out_proj",
>     "fc_in",
>     "fc_out",
>     "wte"
>   ],
>   "task_type": "CAUSAL_LM"
> }
> ```

I get the same error and I have null value in the config as well. I should say that I've disabled pushing to HuggingFace in the peft_adapter.py, but that shouldn't matter when in the example the dpo/final_checkpoint is loading. How to change the search for the final_checkpoint not to be on HuggingFace but to be locally.

**Comment by lvwerra** [comment] 2023-08-23 09:00
If you want to load final checkpoint then the model name should be the full path to the checkpoint. Can you share the code you are running and where the ckeckpoint is saved?

**Comment by lllcc** [comment] 2023-08-26 01:58
> 

however,is any example for peft in trl? thanks for your response

**Comment by lvwerra** [comment] 2023-08-31 14:07
See here: https://huggingface.co/docs/trl/use_model#use-adapters-peft

**Comment by younesbelkada** [comment] 2023-09-27 10:30
Closing for now ! Feel free to re-open if you think the issue is not addressed

**Closed by younesbelkada** 2023-09-27 10:30 UTC
