### ISSUE TITLE
Not find sft.py

### ISSUE THREAD

**Issue by chauncygu** [huggingface/trl#1829] opened 2024-07-12 00:07 UTC
when I run 
`trl sft --model_name_or_path facebook/opt-125m --dataset_name imdb --output_dir opt-sft-imdb`

there is a issue:

`/trl/trl/commands/scripts/sft.py FAILED`

**Comment by qgallouedec** [comment] 2024-08-22 20:46
Thanks for reporting, must be a duplicate of #1716, feel free to comment and add the steps to reproduce if not.

**Closed by qgallouedec** 2024-08-22 20:46 UTC
