### ISSUE TITLE
'NoneType' object is not subscriptable when using phi-1.5

### ISSUE THREAD

**Issue by HassanJbara** [huggingface/trl#1058] opened 2023-12-04 14:24 UTC
I'm running the same code from https://github.com/huggingface/trl/blob/main/examples/scripts/ppo.py, with the only difference being that I replaced gpt-2 with phi-1.5 (https://huggingface.co/microsoft/phi-1_5). Now I'm getting the following error when trying to run the code:

`'NoneType' object is not subscriptable`

![image](https://github.com/huggingface/trl/assets/82707653/fce0276e-2473-4e9d-959a-6e7cb8a99b43)

It appears that the problem lies with `AutoModelForCausalLMWithValueHead`, specifically trying to call the forward function of the model instantiated using `AutoModelForCausalLMWithValueHead` using the TRL library, even though `model.generate` still works. So basically my questions are:

* Is phi-1.5 not supported? Why is that? 
* What can I do to solve this problem? I really would like to use phi-1.5 for my training.

**Comment by lvwerra** [comment] 2023-12-05 10:31
Could you share a full minimal example where you add the model loading logic as well as inputs/generation kwargs?

**Comment by lvwerra** [comment] 2023-12-05 13:29
Indeed I can reproduce. Also it works if we switch `AutoModelForCausalLMWithValueHead` for the vanilla `AutoModelForCausalLM` so there's something off with the value head class. @younesbelkada any ideas?

**Comment by younesbelkada** [comment] 2023-12-06 16:43
I think that model has some bugs in the modeling code which lives on the Hub, if you swtich to this checkpoint : https://huggingface.co/susnato/phi-1_5_dev together with a recent version of transformers everything should work fine as that checkpoint uses the transformers integration

**Comment by HassanJbara** [comment] 2023-12-06 20:19
Is it ok to use a dev checkpoint or should I just wait for this to be fixed?

**Comment by younesbelkada** [comment] 2023-12-07 07:31
I am not sure why that model has a suffix `dev` but should be safe to use IMO, is that correct @susnato?

**Comment by susnato** [comment] 2023-12-07 12:58
Hi, yes it's safe to use. Please excuse me for the naming :) .

**Comment by HassanJbara** [comment] 2023-12-07 13:23
Ok I'll try that later and see how it goes.

**Comment by HassanJbara** [comment] 2023-12-11 12:58
> I think that model has some bugs in the modeling code which lives on the Hub, if you swtich to this checkpoint : https://huggingface.co/susnato/phi-1_5_dev together with a recent version of transformers everything should work fine as that checkpoint uses the transformers integration

Ok, this is not qutie the same thing.

1. The original model requires a package called `einops`, the dev model doesn't. Why is that?
2. I'm also getting this warning for some reason, which doesn't happen when using the original model:
![image](https://github.com/huggingface/trl/assets/82707653/4224d78f-ac57-488d-9275-6755f63ca7a0)

3. Also, the outputs aren't exactly the same. It's not a huge difference, but I'm worried about the performance of the dev model, especially since I don't know what the difference is, exactly.
![image](https://github.com/huggingface/trl/assets/82707653/a9b1e5fe-4012-4500-bd9e-e9f2924b3087)

**Comment by jubueche** [comment] 2023-12-14 12:44
> As I said, this happens if you change the model name in the provided example in `ppo.py` while keeping everything else the same. For a simpler code to reproduce this problem do:
> 
> ```python
> import torch
> from transformers import AutoTokenizer
> from trl import AutoModelForCausalLMWithValueHead
> 
> model = AutoModelForCausalLMWithValueHead.from_pretrained(
>     "microsoft/phi-1_5",
>     trust_remote_code=True,
> )
> 
> tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-1_5")
> tokenizer.pad_token_id = tokenizer.eos_token_id
> 
> query_tensors = tokenizer.encode('this is a test', return_tensors="pt", return_attention_mask=False)
> model(query_tensors)
> ```
> 
> I'm using the latest version of everything, so:
> 
> ```
> accelerate==0.25.0
> numpy ==1.26.0
> pandas==2.1.3
> torch==2.1.1
> torchvision==0.16.1
> transformers==4.35.2
> triton==2.1.0
> trl==0.7.4
> ```
> 
> With python 3.10.13 in a Linux environment with an A100.

Is it correct to use the EOS token ID as the PAD token ID?

**Comment by susnato** [comment] 2023-12-14 19:08
Hi @HassanJbara,

1.  The official repo used `rearrange` and `repeat` from [einops](https://huggingface.co/microsoft/phi-1_5/blob/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py#L15) but we don't need that so we can remove this dependency.
2. Phi uses `CodeGenTokenizer` and as you can see [here](https://github.com/huggingface/transformers/blob/3060899be51fe1a96b12de97376f2e2b8315bc4c/src/transformers/models/codegen/tokenization_codegen.py#L165) the PAD token is not defined so we use the eos token...this should not be a problem and you can ignore that.
3. This is strange because I just tested it and the integration tests are passing so there is no issue from the library side. I think there can be two reasons for this - 
     * The code might have been slightly changed on the repo and it could be different from the time when I wrote those integration test values. or,
     * In each pass the LayerNorms are introducing very little difference and over long sequences it is becoming larger and noticeable. I will try to verify this tomorrow.

**Comment by susnato** [comment] 2023-12-14 19:13
Hi @jubueche, yes I believe it's safe to the EOS token as the PAD token unless it's defined differently in the tokenizer itself.

**Comment by HassanJbara** [comment] 2023-12-14 19:22
> Hi @HassanJbara,
> 
>     1. The official repo used `rearrange` and `repeat` from [einops](https://huggingface.co/microsoft/phi-1_5/blob/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py#L15) but we don't need that so we can remove this dependency.
> 
>     2. Phi uses `CodeGenTokenizer` and as you can see [here](https://github.com/huggingface/transformers/blob/3060899be51fe1a96b12de97376f2e2b8315bc4c/src/transformers/models/codegen/tokenization_codegen.py#L165) the PAD token is not defined so we use the eos token...this should not be a problem and you can ignore that.
> 
>     3. This is strange because I just tested it and the integration tests are passing so there is no issue from the library side. I think there can be two reasons for this -
>        
>        * The code might have been slightly changed on the repo and it could be different from the time when I wrote those integration test values. or,
>        * In each pass the LayerNorms are introducing very little difference and over long sequences it is becoming larger and noticeable. I will try to verify this tomorrow.

I appreciate your reply. It would be nice if this could be included in the phi-1.5-dev readme. I assume I will use the dev model for now and see it goes, but just out of curiosity, why does the original use einops if they are not needed?

**Comment by susnato** [comment] 2023-12-14 20:02
Since `transformers 4.36` has been released, the weight-transfer PRs will be merged soon and you will be able to use it from the official repo!
I don't really know why they used einops but might be due to certain speedups on certain machines?(I might be totally wrong here).

**Comment by HassanJbara** [comment] 2023-12-15 15:11
So I used phi-dev in a test run and I'm getting this error: `RuntimeError: The expanded size of the tensor (640) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [16, 640].  Tensor sizes: [1, 514]`. Also a warning: `Token indices sequence length is longer than the specified maximum sequence length for this model (640 > 512). Running this sequence through the model will result in indexing errors` It's weird, because max_new_tokens is set to 256. Do you have an idea what may be the case? If I change the model, say to gpt-neo, everything works just fine!

**Comment by susnato** [comment] 2023-12-15 15:45
Can you please provide the script? Or maybe the full error message?

**Comment by HassanJbara** [comment] 2023-12-15 16:57
> Can you please provide the script? Or maybe the full error message?

The file could be downloaded using [this link](https://we.tl/t-HWuJUOHBHB). There isn't much to the error message than what I already said, take a look:

![image](https://github.com/huggingface/trl/assets/82707653/c4fece6f-8e56-4c1f-a401-6117fcb6a737)

Try running the script like this: `python ppo.py --ppo_config.log_with wandb`. 

I also keep getting `UserWarning: `return_all_scores` is now deprecated`, but that's a problem with the original script.

**Comment by HassanJbara** [comment] 2023-12-17 08:27
> > Can you please provide the script? Or maybe the full error message?
> 
> The file could be downloaded using [this link](https://we.tl/t-HWuJUOHBHB). There isn't much to the error message than what I already said, take a look:
> 
> ![image](https://private-user-images.githubusercontent.com/82707653/290886672-c4fece6f-8e56-4c1f-a401-6117fcb6a737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDE4MjAsIm5iZiI6MTcwMjgwMTUyMCwicGF0aCI6Ii84MjcwNzY1My8yOTA4ODY2NzItYzRmZWNlNmYtOGU1Ni00YzFmLWE0MDEtNjExN2ZjYjZhNzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA4MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzM2M2M5OGFhMGRhZmYyNzAxYjA4NGY4NDAxNTY5OWU1ODNkMjk0MDc3ZmM2ZjYxZTlkZWRlNjc3MjJhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j-CS6l-i3OcGtGLrcR4Ju-CKaKxCaDGjWQaSt3v6ufE)
> 
> Try running the script like this: `python ppo.py --ppo_config.log_with wandb`.
> 
> I also keep getting `UserWarning: 'return_all_scores' is now deprecated`, but that's a problem with the original script.

Ok, regarding this: adding `"max_length": 512, "truncation": True` to `sent_kwargs` solves the problem. For some reason, `classifier_pipe.preprocess` was returning tensors longer than 512, and this was causing the issue.

**Comment by susnato** [comment] 2023-12-17 10:49
Good catch @HassanJbara! Let me know if you face any other problems.

**Comment by HassanJbara** [comment] 2023-12-17 11:12
> Good catch @HassanJbara! Let me know if you face any other problems.

Thanks :) 
I don't think this is the place for that though, this discussion has already deviated from the original problem. It's safe to close this issue, but I'll leave doing that up to the maintainers.

**Comment by HassanJbara** [comment] 2023-12-17 11:36
Oh, now phi-2 has the same problem >:)

**Comment by susnato** [comment] 2023-12-17 11:37
Are you using from `microsoft`'s repo? @HassanJbara

**Comment by HassanJbara** [comment] 2023-12-17 12:04
> Are you using from `microsoft/phi-2`'s repo? @HassanJbara

Yes, I don’t think there’s a phi-2-dev. I hope the compatibility of TRL improves in the future.

**Comment by susnato** [comment] 2023-12-17 12:14
The weights from the `microsoft/phi-2` are incompatible with the library model.

**Comment by HassanJbara** [comment] 2023-12-17 18:21
> The weights from the `microsoft/phi-2` are incompatible with the library model. You can follow this [issue](https://github.com/huggingface/transformers/issues/28049#issuecomment-1858785861) for that.
> 
> If you want to use phi-2 right now then you have to use it from the Hub.



> The weights from the `microsoft/phi-2` are incompatible with the library model. You can follow this [issue](https://github.com/huggingface/transformers/issues/28049#issuecomment-1858785861) for that.
> 
> If you want to use phi-2 right now then you have to use it from the Hub.

I see. Then you can close this issue after you merge that PR. Thanks for your help!

**Comment by susnato** [comment] 2023-12-17 21:06
Hi @HassanJbara, I just adapted the `phi-2` weights which is compatible with the library.[susnato/phi-2](https://huggingface.co/susnato/phi-2)  

Use this :
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("susnato/phi-2")
tokenizer = AutoTokenizer.from_pretrained("susnato/phi-2")

inputs = tokenizer('''def print_prime(n):
   """
   Print all primes between 1 and n
   """''', return_tensors="pt", return_attention_mask=False)

outputs = model.generate(**inputs, max_length=200)
text = tokenizer.batch_decode(outputs)[0]
print(text)
```

(Make sure to have the latest `transformers` installed before running)

I haven't checked the accuracy of the logits yet but should be within atol=1e-3.

**Comment by susnato** [comment] 2023-12-22 14:10
> I see. Then you can close this issue after you merge that PR. Thanks for your help!

I don't have permission to close issues :), tagging @younesbelkada to close it.

**Comment by lvwerra** [comment] 2023-12-22 15:53
Closing it for you :)

**Comment by susnato** [comment] 2023-12-22 15:54
Thanks!

**Closed by lvwerra** 2023-12-22 15:53 UTC

**Comment by JulesGM** [comment] 2024-01-05 20:51
So the official way to use phi-2 is to use `AutoModelForCausalLMWithValueHead.from_pretrained("susnato/phi-2")` ? @lvwerra

**Comment by susnato** [comment] 2024-01-05 20:54
For now yes, @JulesGM :).

**Comment by JulesGM** [comment] 2024-01-05 21:01
ok thanks!

**Comment by claudiokaserer** [comment] 2024-01-09 01:44
When I try to use susnato/phi-2 with the trl code to do ppo I get the following error.
ValueError: PhiForCausalLM does not support `device_map='auto'`. To implement support, the model class needs to implement the `_no_split_modules` attribute.
Any ideas? I think I need the device_map because if I remove the argument, only the first gpu is used and the memory fills up.

**Comment by JulesGM** [comment] 2024-01-10 16:29
you can maybe try to take inspiration from face/transformers/blob/cef2e40e0f8eaad13b8d32817a48fdddc32eb2a5/src/transformers/models/llama/modeling_llama.py#L851 fork `"susnato/phi-2"` and make the decoder blocks non splittable
